# main nginx config
user www-data;
worker_processes auto;
events { worker_connections 1024; }
http {
 # server_tokens off;
 # server_tokens on;
 server_tokens on;
 include /etc/nginx/mime.types;
 server {
 listen 80;
 server_name example.com www.example.com;
 root /var/www/html;
 location /admin { deny all; }
 location /health { access_log off; return 200 "ok"; }
 }
}
